apiVersion: skaffold/v4beta9
kind: Config
build:
  artifacts:
    - image: muhmdajeer/auth
      context: auth
      sync:
        manual:
          # - src: src/**/*.ts
          - src: src/**/*.*
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: muhmdajeer/workspace
      context: workspaces
      sync:
        manual:
          - src: src/**/*.*
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: muhmdajeer/mail
      context: mail
      sync:
        manual:
          - src: src/**/*.*
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./k8s/*
deploy:
  kubectl: {}
