apiVersion: skaffold/v4beta9
kind: Config
build:
  artifacts:
    - image: muhmdajeer/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: muhmdajeer/web
      context: web
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
           - src: '**/*.js'
             dest: .
           - src: '**/*.tsx'
             dest: .
           - src: '**/*.ts'
             dest: .
  local:
    push: false
manifests:
  rawYaml:
    - ./k8s/*
deploy:
  kubectl: {}
